Allow certain users to Create Company
Coders-HQ/CodersHQ pull request #24
Opened 2021-08-11 15:20 UTC by marrwin

2021-08-15 17:09 UTC, ralsuwaidi requested changes

2021-08-15 17:09 UTC, ralsuwaidi commented on codershq/companies/forms.py
> +class CompanyCreationForm(ModelForm):
better not to leave the comments above, select one of the classes and remove the other when you are confident it works

2021-08-15 17:09 UTC, ralsuwaidi commented on codershq/companies/views.py
> +            name = request.POST['name']
isnt there a better way to save the form? I rememebr the form saving itself without you explicitly taking all the values and creating a new object from them.

2021-08-15 17:09 UTC, ralsuwaidi commented on codershq/users/models.py
> +    allowed_to_create_company = models.BooleanField(default=False)
change this to something shorter, like `is_company` for example

2021-08-15 17:10 UTC, ralsuwaidi commented
overall its a very decent job. Just a few changes and the update view.

2021-08-15 17:23 UTC, gitanimous reviewed
I agree with rashed using something like `is_company` instead of `allowed_to_create_company` would be better, great work man 👍

2021-12-25 16:05 UTC, ralsuwaidi commented
closed PR due to changes not being updated for a while

2021-12-25 16:05 UTC, closed without merging